### PR TITLE
feat: add localization of VDate buttons

### LINKED ISSUE #134: [Feature Request] allow localization of the buttons of the datepicker
Hey there,

Thanks for your work on this library, it's really useful and easy to use.
However, I have a small problem: we want to use the datepicker component on a French website, and, while the month and day labels are configurable through props, the `aria-label` attributes for the "previous/next month/year" buttons are not. This could be easily fixed by allowing customization through props.
I'll submit a PR to fix that if you're okay with it.

Proposal:
add a prop `buttonLabels` with the following format:
```js
{
  selectDate: 'Select Date',
  showCalendar: 'show calendar',
  previousMonth: 'previous month',
  nextMonth: 'next month',
  previousYear: 'previous year',
  nextYear: 'next year',
}
```

edit: added the "Select Date" and "show calendar" buttons that I missed

### PR DESCRIPTION
**Pull request by bcourtel**
fixes #134 

I had several ESLint errors from lines not edited in this PR, I can fix them in another PR in you want me to:

<details>
<summary>ESLint errors and warnings</summary>

    ✖ eslint --fix src:

    /src/components/VDate/VDate.vue
    10:65  error    Replace `>&#x1F4C5;</span` with `⏎··········>&#x1F4C5;</span⏎········`  prettier/prettier
    35:38  error    Replace `⏎&#8606;⏎` with `·&#8606;·`                                    prettier/prettier
    36:1   warning  Expected indentation of 12 spaces but found 0 spaces                    vue/html-indent
    37:1   warning  Expected indentation of 10 spaces but found 0 spaces                    vue/html-indent
    46:39  error    Replace `⏎&#8592;⏎` with `·&#8592;·`                                    prettier/prettier
    47:1   warning  Expected indentation of 12 spaces but found 0 spaces                    vue/html-indent
    48:1   warning  Expected indentation of 10 spaces but found 0 spaces                    vue/html-indent
    64:39  error    Replace `⏎&#8594;⏎` with `·&#8594;·`                                    prettier/prettier
    65:1   warning  Expected indentation of 12 spaces but found 0 spaces                    vue/html-indent
    66:1   warning  Expected indentation of 10 spaces but found 0 spaces                    vue/html-indent
    75:38  error    Replace `⏎&#8608;⏎` with `·&#8608;·`                                    prettier/prettier
    76:1   warning  Expected indentation of 12 spaces but found 0 spaces                    vue/html-indent
    77:1   warning  Expected indentation of 10 spaces but found 0 spaces                    vue/html-indent

    /src/composables/useForm.js
    51:0  warning  Missing JSDoc @property "validate" description  jsdoc/require-property-description

    ✖ 14 problems (5 errors, 9 warnings)
    5 errors and 8 warnings potentially fixable with the `--fix` option.

</details>

### CODE REVIEW

**Comment by PoOw** [comment]
Look's good to me ! You could add this feature to the documentation so that other users can benefit from it !

**Comment by bcourtel** [comment]
@PoOw Good idea! I added documentation about this feature

**Comment by AustinGil** [comment]
This looks good to me. I still don't have automated deploys set up, so please change the target branch to `develop`. That will give me some time to test it out and prepare a release for it.

Thanks @PoOw for calling out the documentation additions. Very helpful :)

**Comment by bcourtel** [comment]
Thank you! Target branch changed

**Pull request merged**
