### PR TITLE
adding intersect directive

### PR DESCRIPTION
**Pull request by mahmoudyusof**
I thought since we need some way of telling weather something is visible on the screen or not so we can for example animate it, that we could make our lives easier by making it a directive.
I haven't built it yet, and the code could be modified. I hope you give it a look and give me feedback that would be swell.

### CODE REVIEW

**Comment by Stegosource** [comment]
This is a good idea. Have you seen the Intersect component? https://github.com/Stegosource/vuetensils/tree/master/src/components/VIntersect

I actually played around with writing this directive myself, but I decided not to after all. I don't remember why. But if we're going to add this, I'd like to keep parity with the component. So maybe call it `v-intersect`? 

More importantly, however, is that it should support the same functions. So maybe rather than
```
<div class="some-div-down-below" v-scroll="seen">...</div>
```
It's like 
```
<div class="some-div-down-below" v-intersect="{ onChange: () => {},  onEnter: () => {},  onLeave: () => {},  }">...</div>
```
And we could provide modifiers to the directive
```
<div class="some-div-down-below" v-intersect.change="onChange">...</div>
<div class="some-div-down-below" v-intersect.enter="onEnter">...</div>
<div class="some-div-down-below" v-intersect.leave="onLeave">...</div>
```

How do you feel about that?

**Comment by mahmoudyusof** [comment]
Yeah I apologize I haven't seen the intersect component, this was actually inspired by the VImg component.
Your ideas are awesome, I actually prefer the object syntax rather than modifiers way. because as far as I understand -and this could be wrong- this way we can add all functionality to one element without making multiple intersection observer objects, am I right ?
and thanks for considering my code :D

**Comment by mahmoudyusof** [comment]
Yeah I apologize I haven't seen the intersect component, this was actually inspired by the VImg component.
Your ideas are awesome, I actually prefer the object syntax rather than modifiers way. because as far as I understand -and this could be wrong- this way we can add all functionality to one element without making multiple intersection observer objects, am I right ?
and thanks for considering my code :D

**Comment by Stegosource** [comment]
Yeah. well my suggestion would be to support both object syntax and modifiers. As I imagine myself using it, there are times when I would want a lot of flexibility. So I would reach for the object syntax. But then there are times when I simply want to do something on enter. And the modifier approach seems simpler.

If you want to tackle this, I'm happy to provide guidance/feedback. Otherwise, I think it's worth adding and I can do it when I can get to it. Currently working on another project though.

**Comment by mahmoudyusof** [comment]
I would really appreciate your feedback and guidance. I will work on it.
thanks a lot :)

**Comment by mahmoudyusof** [comment]
I would really appreciate your feedback and guidance. I will work on it.
thanks a lot :)

**Comment by mahmoudyusof** [comment]
I did as you suggested. I would love if you look at it, try it and give me feedback whenever you have time, I am not in a hurry, actually I have final exams now :,D

**Comment by Stegosource** [comment]
Hey, @mahmoudyusof, can you change the target branch for the PR to `develop` instead of `master`. I only put things into `master` once they are published to NPM, but that allows me to work off `develop` for a while without creating some disparity between the published project and what is on the documentation site.

**Comment by mahmoudyusof** [comment]
Sure thing. done.

**Comment by Stegosource** [comment]
Hey @mahmoudyusof I'm finally getting some time to look into this. There are some changes I would like to propose, but I think there is a bit extra conflict since it was originally branched from `master`.

take a look at this and let me know what you think:
```
export default {
  inserted(el, binding) {
    const options = {
      ...binding.value,
    }
    const listeners = {
      onEnter: binding.value.onEnter,
      onExit: binding.value.onExit,
      onChange: binding.value.onChange,
    }

    // Support passing direct function
    if (binding.value instanceof Function) {
      const { enter, exit, change } = binding.modifiers
      listeners.onEnter = enter && binding.value
      listeners.onExit = exit && binding.value
      listeners.onChange = change && binding.value
    }

    const observer = new IntersectionObserver(entries => {
      const { isIntersecting } = entries[0]
      if (isIntersecting) {
        listeners.onEnter && listeners.onEnter(el)
      } else {
        listeners.onExit && listeners.onExit(el)
      }
      listeners.onChange && listeners.onChange(el, isIntersecting)
    }, options)
    observer.observe(el)
  },
}
```

**Comment by mahmoudyusof** [comment]
works like a charm, however, there is something I want to talk about. the intersectionObserver invokes the callback on load. I've removed this behaviour by using a flag. I wanted to know if you want such behaviour.
this is the final code.
```
export default {
    inserted: (el, binding) => {
        const options = {
            ...binding.value
        };
 
        var onLoadCall = false;

        options.root = options.root && document.querySelector(options.root);

        const listeners = {
            onEnter: binding.value.onEnter,
            onLeave: binding.value.onLeave,
            onChange: binding.value.onChange
        }
        
        if(binding.value instanceof Function){
            const { enter, leave, change } = binding.modifiers
            listeners.onEnter = enter && binding.value;
            listeners.onChange = change && binding.value;
            listeners.onLeave = leave && binding.value;
        }

        const observer = new IntersectionObserver((entries) => {
            if(!onLoadCall){
                const { isIntersecting } = entries[0];
                if(isIntersecting){
                    listeners.onEnter && listeners.onEnter(el);
                }else{
                    listeners.onLeave && listeners.onLeave(el);
                }
                listeners.onChange && listeners.onChange(el, isIntersecting);
            }else{
                onLoadCall = false;
            }
        }, options);
        observer.observe(el);
    }
}
```
thanks for your time. :smiley:

**Comment by Stegosource** [comment]
Yeah, the way I got around that was by passing the handler like so:
`<div v-intersect.enter="() => $log('hello')"></div>`

In you example it looks like `onLoadCall` is set to false and will always remain false

**Comment by mahmoudyusof** [comment]
yeah, sorry it is initially true not false. my code is correct but when I edited the code in the example above, I didn't do it right, my bad :sweat_smile:  . the code is running well though. I edited the comment to have the right code now.

**Comment by Stegosource** [comment]
Cool. The file `src/directives/intersect.js` in the changes tab still looks like the old version. But if you want to push up the new changes, I'll approve :)

**Comment by mahmoudyusof** [comment]
yeah I wasn't working on the master branch of my repo. I've just merged the changes. :)

**Comment by Stegosource** [comment]
Nice. I'll be adding this to the next minor release alongside a datatables component I'm hoping to finish soon.

**Comment by mahmoudyusof** [comment]
best of luck, I really want to thank you for your patience and guidance. really appreciate it.

**Pull request merged**
